apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-service
  namespace: ticketing
  labels:
    app: availability-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: availability-service
  template:
    metadata:
      labels:
        app: availability-service
    spec:
      containers:
        - name: availability-service
          image: ticketing/availability-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: catalog.service.url
              value: "http://catalog-service:8081"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: availability-service
  namespace: ticketing
spec:
  selector:
    app: availability-service
  ports:
    - port: 8082
      targetPort: 8082
