apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ticketing
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ticketing/order-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "ticketing_orders"
            - name: POSTGRES_USER
              value: "ticketing"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: JWT_SECRET
              value: "dev-secret-change-this-key-dev-secret-change-this-key"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ticketing
spec:
  selector:
    app: order-service
  ports:
    - port: 8084
      targetPort: 8084
