spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: reservation-service
  kafka:
    consumer:
      group-id: reservation-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
server:
  port: 8083

availability:
  service:
    url: ${AVAILABILITY_SERVICE_URL:http://localhost:8082}
